---
kdx_config_path: /etc/kronosdx/config.yml
kdx_data_root: /kdx-data
kdx_storage_apply: false
rustfs_container_name: rustfs
rustfs_env_file: /etc/kronosdx/secrets/rustfs.env
rustfs_image: rustfs/rustfs:latest
rustfs_pull_image: true
rustfs_start: true
rustfs_api_port: 9000
rustfs_console_port: 9001
wizard_port: 8443
